name_or_path: unicamp-dl/mmarco
lazy: true
config: russian
labels_field: query
content_field: positive
split: train
limit: null
chunk_id_col: null
keywords_col: null
keywords_nested_col: null
explanation_nested_col: null
