name_or_path: justatom/meme-russian-ir
labels_field: null
content_field: description
split: train
limit: null
chunk_id_col: id
drop_columns:
  - photos
keywords_col: null
keywords_nested_col: null
explanation_nested_col: null
