name: Deploy docs

on:
  push:
    branches: [ master ]

permissions:
  contents: write

jobs:
  deploy-docs:
    name: Deploy documentation
    uses: ./.github/workflows/docs-reusable.yaml
    with:
      deploy: true
